package events

const (
	TagTaskID    = "t"
	TagAgent     = "agent"
	TagStage     = "stage"
	TagRecipient = "p"
	TagDedupe    = "d"
	TagRef       = "ref"
	TagSession   = "session"
	TagKind      = "k"
	TagRole      = "role"
	TagTopic     = "topic"
	TagKeyword   = "keyword"
	TagSource    = "source"
	TagGoal       = "goal"
	TagRunID      = "run"
	TagMemType    = "mem_type"
	TagMemTaskID  = "task_id"
	TagMemSource  = "mem_source"
	TagFeedback         = "feedback"
	TagFeedbackSource   = "fb_source"
	TagFeedbackSeverity = "fb_severity"
	TagFeedbackCategory = "fb_category"
	TagStepID           = "step_id"
	TagProposal         = "proposal"
	TagProposalKind     = "prop_kind"
	TagProposalStatus   = "prop_status"
	TagRetro            = "retro"
	TagRetroTrigger     = "retro_trigger"
	TagRetroOutcome     = "retro_outcome"
)
